public without sharing class Constants {
    
    // These variables are introduced with respect to Candidate portal
    public static string CANDIDATE_SITE             =' ';// System.label.CandidateSiteURL;
    public static final String CANDIDATE            = 'Candidate';
    public static final String APPCANDIDATESTAGE    = 'Applied';
    public static final String TEMP_URL_SENT_CONFIRMATION    = 'Temporary URL sent successfully';
    public static final String ERROR_MSG    = 'Error';
    public static final String CONTACT_ONDONTE    = 'Some Error Occurred - Please Contact your Ondonte Team !!!';
    public static final String RECORD_UPDATE_SUCCESS    = 'Record Updated Successfully !!!';
    public static final String SHIFT_STATUS_ALLOCATED    = 'Allocated';
    public static final String emailTempNameToNotifyCandidateOnShiftChange    = 'Final Candidate Notification to Candidate';
    public static final String emailTempNameToNotifyClientOnShiftChange    = 'Final Candidate Notification';
    public static final String ReferalEmailTemplate    = 'Referral_Email_to_Candidate';
    public static final String ApplicationStatusRejected    = 'Rejected by Client';
    public static final String ApplicationStatusSelected    = 'Selected by Client';
    public static final String ApplicationStatusInterviewScheduled    = 'Interview Scheduled';	
}