public class WrapperClass {

    public String C_FirstName;
    public String C_LastName;
    public String C_AccName;
    public String C_MaillingAdd;
    public String C_Phone;
    public String C_Email;
    public String C_MobilePhone;
    
    public String W_Name;
    public String W_CandidateName;
    public String W_Duration;
    public String W_Employer;
    public String W_jobTitle;
    public Date W_StartDate;
    public String W_EmployerName;
    public Date W_EndDate;
    public String W_Contact;
    
    public String E_Candidate;
    public String E_CourseDescription;
    public Date E_EndYear;
    public String E_CourseName;
    public Date E_StartYear;
    public String E_UniversityCollageName;
    
    public String Cr_Name;
    public Date Cr_EndDate;
    public Date Cr_StartDate;
    public Date Cr_ExpiryDate;
   
    public WrapperClass(){
        
    }
   
}